export const regularAST = {
  type: "File",
  start: 0,
  end: 265,
  loc: { start: { line: 1, column: 0, index: 0 }, end: { line: 13, column: 4, index: 265 } },
  errors: [],
  program: {
    type: "Program",
    start: 0,
    end: 265,
    loc: { start: { line: 1, column: 0, index: 0 }, end: { line: 13, column: 4, index: 265 } },
    sourceType: "module",
    interpreter: null,
    body: [
      {
        type: "ImportDeclaration",
        start: 7,
        end: 45,
        loc: { start: { line: 2, column: 6, index: 7 }, end: { line: 2, column: 44, index: 45 } },
        importKind: "value",
        specifiers: [
          {
            type: "ImportDefaultSpecifier",
            start: 14,
            end: 20,
            loc: { start: { line: 2, column: 13, index: 14 }, end: { line: 2, column: 19, index: 20 } },
            local: {
              type: "Identifier",
              start: 14,
              end: 20,
              loc: {
                start: { line: 2, column: 13, index: 14 },
                end: { line: 2, column: 19, index: 20 },
                identifierName: "styled",
              },
              name: "styled",
            },
          },
          {
            type: "ImportSpecifier",
            local: { type: "Identifier", name: "styled" },
            imported: { type: "Identifier", name: "styled" },
          },
        ],
        source: {
          type: "StringLiteral",
          start: 26,
          end: 45,
          loc: { start: { line: 2, column: 25, index: 26 }, end: { line: 2, column: 44, index: 45 } },
          extra: { rawValue: "styled-components", raw: "'styled-components'" },
          value: "styled-components",
        },
      },
      {
        type: "VariableDeclaration",
        start: 53,
        end: 260,
        loc: { start: { line: 4, column: 6, index: 53 }, end: { line: 12, column: 7, index: 260 } },
        declarations: [
          {
            type: "VariableDeclarator",
            start: 59,
            end: 260,
            loc: { start: { line: 4, column: 12, index: 59 }, end: { line: 12, column: 7, index: 260 } },
            id: {
              type: "Identifier",
              start: 59,
              end: 65,
              loc: {
                start: { line: 4, column: 12, index: 59 },
                end: { line: 4, column: 18, index: 65 },
                identifierName: "Button",
              },
              name: "Button",
            },
            init: {
              type: "TaggedTemplateExpression",
              start: 68,
              end: 260,
              loc: { start: { line: 4, column: 21, index: 68 }, end: { line: 12, column: 7, index: 260 } },
              tag: {
                type: "MemberExpression",
                start: 68,
                end: 81,
                loc: { start: { line: 4, column: 21, index: 68 }, end: { line: 4, column: 34, index: 81 } },
                object: {
                  type: "Identifier",
                  start: 68,
                  end: 74,
                  loc: {
                    start: { line: 4, column: 21, index: 68 },
                    end: { line: 4, column: 27, index: 74 },
                    identifierName: "styled",
                  },
                  name: "styled",
                },
                computed: false,
                property: {
                  type: "Identifier",
                  start: 75,
                  end: 81,
                  loc: {
                    start: { line: 4, column: 28, index: 75 },
                    end: { line: 4, column: 34, index: 81 },
                    identifierName: "button",
                  },
                  name: "button",
                },
              },
              quasi: {
                type: "TemplateLiteral",
                start: 81,
                end: 260,
                loc: { start: { line: 4, column: 34, index: 81 }, end: { line: 12, column: 7, index: 260 } },
                expressions: [],
                quasis: [
                  {
                    type: "TemplateElement",
                    start: 82,
                    end: 259,
                    loc: { start: { line: 4, column: 35, index: 82 }, end: { line: 12, column: 6, index: 259 } },
                    value: {
                      raw: "\n        background: white;\n        color: palevioletred;\n        font-size: 1em;\n        &:hover {\n          background: palevioletred;\n          color: white;\n        }\n      ",
                      cooked:
                        "\n        background: white;\n        color: palevioletred;\n        font-size: 1em;\n        &:hover {\n          background: palevioletred;\n          color: white;\n        }\n      ",
                    },
                    tail: true,
                  },
                ],
              },
            },
          },
        ],
        kind: "const",
      },
    ],
    directives: [],
  },
  comments: [],
}

export const multipleDeclarationsAST = {
  type: "File",
  start: 0,
  end: 427,
  loc: { start: { line: 1, column: 0, index: 0 }, end: { line: 15, column: 4, index: 427 } },
  errors: [],
  program: {
    type: "Program",
    start: 0,
    end: 427,
    loc: { start: { line: 1, column: 0, index: 0 }, end: { line: 15, column: 4, index: 427 } },
    sourceType: "module",
    interpreter: null,
    body: [
      {
        type: "VariableDeclaration",
        start: 7,
        end: 333,
        loc: { start: { line: 2, column: 6, index: 7 }, end: { line: 9, column: 7, index: 333 } },
        declarations: [
          {
            type: "VariableDeclarator",
            start: 13,
            end: 333,
            loc: { start: { line: 2, column: 12, index: 13 }, end: { line: 9, column: 7, index: 333 } },
            id: {
              type: "Identifier",
              start: 13,
              end: 19,
              loc: {
                start: { line: 2, column: 12, index: 13 },
                end: { line: 2, column: 18, index: 19 },
                identifierName: "Button",
              },
              name: "Button",
            },
            init: {
              type: "TaggedTemplateExpression",
              start: 22,
              end: 333,
              loc: { start: { line: 2, column: 21, index: 22 }, end: { line: 9, column: 7, index: 333 } },
              tag: {
                type: "MemberExpression",
                start: 22,
                end: 35,
                loc: { start: { line: 2, column: 21, index: 22 }, end: { line: 2, column: 34, index: 35 } },
                object: {
                  type: "Identifier",
                  start: 22,
                  end: 28,
                  loc: {
                    start: { line: 2, column: 21, index: 22 },
                    end: { line: 2, column: 27, index: 28 },
                    identifierName: "styled",
                  },
                  name: "styled",
                },
                computed: false,
                property: {
                  type: "Identifier",
                  start: 29,
                  end: 35,
                  loc: {
                    start: { line: 2, column: 28, index: 29 },
                    end: { line: 2, column: 34, index: 35 },
                    identifierName: "button",
                  },
                  name: "button",
                },
              },
              quasi: {
                type: "TemplateLiteral",
                start: 35,
                end: 333,
                loc: { start: { line: 2, column: 34, index: 35 }, end: { line: 9, column: 7, index: 333 } },
                expressions: [
                  {
                    type: "ArrowFunctionExpression",
                    start: 59,
                    end: 100,
                    loc: { start: { line: 3, column: 22, index: 59 }, end: { line: 3, column: 63, index: 100 } },
                    id: null,
                    generator: false,
                    async: false,
                    params: [
                      {
                        type: "Identifier",
                        start: 59,
                        end: 64,
                        loc: {
                          start: { line: 3, column: 22, index: 59 },
                          end: { line: 3, column: 27, index: 64 },
                          identifierName: "props",
                        },
                        name: "props",
                      },
                    ],
                    body: {
                      type: "ConditionalExpression",
                      start: 68,
                      end: 100,
                      loc: { start: { line: 3, column: 31, index: 68 }, end: { line: 3, column: 63, index: 100 } },
                      test: {
                        type: "MemberExpression",
                        start: 68,
                        end: 81,
                        loc: { start: { line: 3, column: 31, index: 68 }, end: { line: 3, column: 44, index: 81 } },
                        object: {
                          type: "Identifier",
                          start: 68,
                          end: 73,
                          loc: {
                            start: { line: 3, column: 31, index: 68 },
                            end: { line: 3, column: 36, index: 73 },
                            identifierName: "props",
                          },
                          name: "props",
                        },
                        computed: false,
                        property: {
                          type: "Identifier",
                          start: 74,
                          end: 81,
                          loc: {
                            start: { line: 3, column: 37, index: 74 },
                            end: { line: 3, column: 44, index: 81 },
                            identifierName: "primary",
                          },
                          name: "primary",
                        },
                      },
                      consequent: {
                        type: "StringLiteral",
                        start: 84,
                        end: 90,
                        loc: { start: { line: 3, column: 47, index: 84 }, end: { line: 3, column: 53, index: 90 } },
                        extra: { rawValue: "blue", raw: "'blue'" },
                        value: "blue",
                      },
                      alternate: {
                        type: "StringLiteral",
                        start: 93,
                        end: 100,
                        loc: { start: { line: 3, column: 56, index: 93 }, end: { line: 3, column: 63, index: 100 } },
                        extra: { rawValue: "white", raw: "'white'" },
                        value: "white",
                      },
                    },
                  },
                  {
                    type: "ArrowFunctionExpression",
                    start: 120,
                    end: 162,
                    loc: { start: { line: 4, column: 17, index: 120 }, end: { line: 4, column: 59, index: 162 } },
                    id: null,
                    generator: false,
                    async: false,
                    params: [
                      {
                        type: "Identifier",
                        start: 120,
                        end: 125,
                        loc: {
                          start: { line: 4, column: 17, index: 120 },
                          end: { line: 4, column: 22, index: 125 },
                          identifierName: "props",
                        },
                        name: "props",
                      },
                    ],
                    body: {
                      type: "ConditionalExpression",
                      start: 129,
                      end: 162,
                      loc: { start: { line: 4, column: 26, index: 129 }, end: { line: 4, column: 59, index: 162 } },
                      test: {
                        type: "MemberExpression",
                        start: 129,
                        end: 142,
                        loc: { start: { line: 4, column: 26, index: 129 }, end: { line: 4, column: 39, index: 142 } },
                        object: {
                          type: "Identifier",
                          start: 129,
                          end: 134,
                          loc: {
                            start: { line: 4, column: 26, index: 129 },
                            end: { line: 4, column: 31, index: 134 },
                            identifierName: "props",
                          },
                          name: "props",
                        },
                        computed: false,
                        property: {
                          type: "Identifier",
                          start: 135,
                          end: 142,
                          loc: {
                            start: { line: 4, column: 32, index: 135 },
                            end: { line: 4, column: 39, index: 142 },
                            identifierName: "primary",
                          },
                          name: "primary",
                        },
                      },
                      consequent: {
                        type: "StringLiteral",
                        start: 145,
                        end: 152,
                        loc: { start: { line: 4, column: 42, index: 145 }, end: { line: 4, column: 49, index: 152 } },
                        extra: { rawValue: "white", raw: "'white'" },
                        value: "white",
                      },
                      alternate: {
                        type: "StringLiteral",
                        start: 155,
                        end: 162,
                        loc: { start: { line: 4, column: 52, index: 155 }, end: { line: 4, column: 59, index: 162 } },
                        extra: { rawValue: "black", raw: "'black'" },
                        value: "black",
                      },
                    },
                  },
                  {
                    type: "Identifier",
                    start: 186,
                    end: 194,
                    loc: {
                      start: { line: 5, column: 21, index: 186 },
                      end: { line: 5, column: 29, index: 194 },
                      identifierName: "fontSize",
                    },
                    name: "fontSize",
                  },
                  {
                    type: "ArrowFunctionExpression",
                    start: 254,
                    end: 295,
                    loc: { start: { line: 7, column: 28, index: 254 }, end: { line: 7, column: 69, index: 295 } },
                    id: null,
                    generator: false,
                    async: false,
                    params: [
                      {
                        type: "Identifier",
                        start: 254,
                        end: 259,
                        loc: {
                          start: { line: 7, column: 28, index: 254 },
                          end: { line: 7, column: 33, index: 259 },
                          identifierName: "props",
                        },
                        name: "props",
                      },
                    ],
                    body: {
                      type: "ConditionalExpression",
                      start: 263,
                      end: 295,
                      loc: { start: { line: 7, column: 37, index: 263 }, end: { line: 7, column: 69, index: 295 } },
                      test: {
                        type: "MemberExpression",
                        start: 263,
                        end: 276,
                        loc: { start: { line: 7, column: 37, index: 263 }, end: { line: 7, column: 50, index: 276 } },
                        object: {
                          type: "Identifier",
                          start: 263,
                          end: 268,
                          loc: {
                            start: { line: 7, column: 37, index: 263 },
                            end: { line: 7, column: 42, index: 268 },
                            identifierName: "props",
                          },
                          name: "props",
                        },
                        computed: false,
                        property: {
                          type: "Identifier",
                          start: 269,
                          end: 276,
                          loc: {
                            start: { line: 7, column: 43, index: 269 },
                            end: { line: 7, column: 50, index: 276 },
                            identifierName: "primary",
                          },
                          name: "primary",
                        },
                      },
                      consequent: {
                        type: "StringLiteral",
                        start: 279,
                        end: 285,
                        loc: { start: { line: 7, column: 53, index: 279 }, end: { line: 7, column: 59, index: 285 } },
                        extra: { rawValue: "blue", raw: "'blue'" },
                        value: "blue",
                      },
                      alternate: {
                        type: "StringLiteral",
                        start: 288,
                        end: 295,
                        loc: { start: { line: 7, column: 62, index: 288 }, end: { line: 7, column: 69, index: 295 } },
                        extra: { rawValue: "black", raw: "'black'" },
                        value: "black",
                      },
                    },
                  },
                ],
                quasis: [
                  {
                    type: "TemplateElement",
                    start: 36,
                    end: 57,
                    loc: { start: { line: 2, column: 35, index: 36 }, end: { line: 3, column: 20, index: 57 } },
                    value: { raw: "\n        background: ", cooked: "\n        background: " },
                    tail: false,
                  },
                  {
                    type: "TemplateElement",
                    start: 101,
                    end: 118,
                    loc: { start: { line: 3, column: 64, index: 101 }, end: { line: 4, column: 15, index: 118 } },
                    value: { raw: ";\n        color: ", cooked: ";\n        color: " },
                    tail: false,
                  },
                  {
                    type: "TemplateElement",
                    start: 163,
                    end: 184,
                    loc: { start: { line: 4, column: 60, index: 163 }, end: { line: 5, column: 19, index: 184 } },
                    value: { raw: ";\n        font-size: ", cooked: ";\n        font-size: " },
                    tail: false,
                  },
                  {
                    type: "TemplateElement",
                    start: 195,
                    end: 252,
                    loc: { start: { line: 5, column: 30, index: 195 }, end: { line: 7, column: 26, index: 252 } },
                    value: {
                      raw: ";\n        padding: 0.25em 1em;\n        border: 2px solid ",
                      cooked: ";\n        padding: 0.25em 1em;\n        border: 2px solid ",
                    },
                    tail: false,
                  },
                  {
                    type: "TemplateElement",
                    start: 296,
                    end: 332,
                    loc: { start: { line: 7, column: 70, index: 296 }, end: { line: 9, column: 6, index: 332 } },
                    value: {
                      raw: ";\n        border-radius: 3px;\n      ",
                      cooked: ";\n        border-radius: 3px;\n      ",
                    },
                    tail: true,
                  },
                ],
              },
            },
          },
        ],
        kind: "const",
      },
      {
        type: "VariableDeclaration",
        start: 341,
        end: 422,
        loc: { start: { line: 11, column: 6, index: 341 }, end: { line: 14, column: 7, index: 422 } },
        declarations: [
          {
            type: "VariableDeclarator",
            start: 347,
            end: 422,
            loc: { start: { line: 11, column: 12, index: 347 }, end: { line: 14, column: 7, index: 422 } },
            id: {
              type: "Identifier",
              start: 347,
              end: 353,
              loc: {
                start: { line: 11, column: 12, index: 347 },
                end: { line: 11, column: 18, index: 353 },
                identifierName: "Header",
              },
              name: "Header",
            },
            init: {
              type: "TaggedTemplateExpression",
              start: 356,
              end: 422,
              loc: { start: { line: 11, column: 21, index: 356 }, end: { line: 14, column: 7, index: 422 } },
              tag: {
                type: "MemberExpression",
                start: 356,
                end: 365,
                loc: { start: { line: 11, column: 21, index: 356 }, end: { line: 11, column: 30, index: 365 } },
                object: {
                  type: "Identifier",
                  start: 356,
                  end: 362,
                  loc: {
                    start: { line: 11, column: 21, index: 356 },
                    end: { line: 11, column: 27, index: 362 },
                    identifierName: "styled",
                  },
                  name: "styled",
                },
                computed: false,
                property: {
                  type: "Identifier",
                  start: 363,
                  end: 365,
                  loc: {
                    start: { line: 11, column: 28, index: 363 },
                    end: { line: 11, column: 30, index: 365 },
                    identifierName: "h1",
                  },
                  name: "h1",
                },
              },
              quasi: {
                type: "TemplateLiteral",
                start: 365,
                end: 422,
                loc: { start: { line: 11, column: 30, index: 365 }, end: { line: 14, column: 7, index: 422 } },
                expressions: [],
                quasis: [
                  {
                    type: "TemplateElement",
                    start: 366,
                    end: 421,
                    loc: { start: { line: 11, column: 31, index: 366 }, end: { line: 14, column: 6, index: 421 } },
                    value: {
                      raw: "\n        font-size: 1rem;\n        padding: 4rem;\n      ",
                      cooked: "\n        font-size: 1rem;\n        padding: 4rem;\n      ",
                    },
                    tail: true,
                  },
                ],
              },
            },
          },
        ],
        kind: "const",
      },
    ],
    directives: [],
  },
  comments: [],
}

export const nestedTemplateAST = {
  type: "TaggedTemplateExpression",
  tag: {
    type: "MemberExpression",
    object: {
      type: "Identifier",
      name: "styled",
    },
    property: {
      type: "Identifier",
      name: "section",
    },
  },
  quasi: {
    type: "TemplateLiteral",
    quasis: [
      {
        type: "TemplateElement",
        value: {
          raw: "\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  height: 100vh;\n  background: linear-gradient(\n    145deg,\n    rgba(253, 38, 71, 1) 0%,\n    rgba(252, 128, 45, 1) 75%,\n    rgba(250, 167, 43, 1) 100%\n  );\n\n  ",
          cooked:
            "\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  height: 100vh;\n  background: linear-gradient(\n    145deg,\n    rgba(253, 38, 71, 1) 0%,\n    rgba(252, 128, 45, 1) 75%,\n    rgba(250, 167, 43, 1) 100%\n  );\n\n  ",
        },
        tail: false,
      },
      {
        type: "TemplateElement",
        value: {
          raw: "\n\n  ",
          cooked: "\n\n  ",
        },
        tail: false,
      },
      {
        type: "TemplateElement",
        value: {
          raw: "\n",
          cooked: "\n",
        },
        tail: true,
      },
    ],
    expressions: [
      {
        type: "TaggedTemplateExpression",
        tag: {
          type: "Identifier",
          name: "css",
        },
        quasi: {
          type: "TemplateLiteral",
          quasis: [
            {
              type: "TemplateElement",
              value: {
                raw: "\n    margin-bottom: 2em;\n  ",
                cooked: "\n    margin-bottom: 2em;\n  ",
              },
              tail: true,
            },
          ],
          expressions: [],
        },
      },
    ],
  },
}
